//
// created by andrew on 3/6/26
//
#ifndef IPFIX_IPFIX_STRUCT_H
#define IPFIX_IPFIX_STRUCT_H
#include <asm-generic/types.h>

struct ipfix_record {
 __u64 octet_delta_count;
 __u64 packet_delta_count;
 __u64 delta_flow_count;
 __u8 protocol_identifier;
 __u8 ip_class_of_service;
 __u16 tcp_control_bits;
 __u16 source_transport_port;
 __u32 source_ipv4_address;
__u8 source_ipv4_prefix_length;
__u32 ingress_interface;
__u16 destination_transport_port;
__u32 destination_ipv4_address;
__u8 destination_ipv4_prefix_length;
__u32 egress_interface;
__u32 ip_nexthop_ipv4_address;
__u32 bgp_source_as_number;
__u32 bgp_destination_as_number;
__u32 bgp_nexthop_ipv4_address;
__u64 post_mcast_packet_delta_count;
__u64 post_mcast_octet_delta_count;
__u32 flow_end_sys_uptime;
__u32 flow_start_sys_uptime;
__u64 post_octet_delta_count;
__u64 post_packet_delta_count;
__u64 minimum_ip_total_length;
__u64 maximum_ip_total_length;
unsigned char source_ipv6_address[16];
unsigned char destination_ipv6_address[16];
__u8 source_ipv6_prefix_length;
__u8 destination_ipv6_prefix_length;
__u32 flow_label_ipv6;
__u16 icmp_type_code_ipv4;
__u8 igmp_type;
__u32 sampling_interval;
__u8 sampling_algorithm;
__u16 flow_active_timeout;
__u16 flow_idle_timeout;
__u8 engine_type;
__u8 engine_id;
__u64 exported_octet_total_count;
__u64 exported_message_total_count;
__u64 exported_flow_record_total_count;
__u32 source_ipv4_prefix;
__u32 destination_ipv4_prefix;
__u8 mpls_top_label_type;
__u32 mpls_top_label_ipv4_address;
__u8 sampler_id;
__u8 sampler_mode;
__u32 sampler_random_interval;
__u8 class_id;
__u8 minimum_ttl;
__u8 maximum_ttl;
__u32 fragment_identification;
__u8 post_ip_class_of_service;
unsigned char source_mac_address[6];
unsigned char post_destination_mac_address[6];
__u16 vlan_id;
__u16 post_vlan_id;
__u8 ip_version;
__u8 flow_direction;
unsigned char ip_nexthop_ipv6_address[16];
unsigned char bgp_nexthop_ipv6_address[16];
__u32 ipv6_extension_headers;
unsigned char destination_mac_address[6];
unsigned char post_source_mac_address[6];
char interface_name[1024];
char interface_description[1024];
char sampler_name[1024];
__u64 octet_total_count;
__u64 packet_total_count;
__u32 flags_and_sampler_id;
__u16 fragment_offset;
__u32 forwarding_status;
unsigned char mpls_vpn_route_distinguisher[256];
__u8 mpls_top_label_prefix_length;
__u32 src_traffic_index;
__u32 dst_traffic_index;
unsigned char  application_description[1024];
unsigned char application_id[256];
unsigned char application_name[256];
 __u8 post_ip_diffserv_codepoint;
__u32  multicast_replication_factor;
unsigned char classname[1024];
__u8 classification_engine_id;
__u16 layer2_packet_section_offset;
__u16 layer2_packet_section_size;
unsigned char layer2_packet_section_data[1024];
__u32 bgp_next_adjacent_as_number;
__u32 bgp_prev_adjacent_as_number;
__u32 exporter_ipv4_address;
unsigned char exporter_ipv6_address[16];
__u64 dropped_octet_delta_count;
__u64 dropped_packet_delta_count;
__u64 dropped_octet_total_count;
__u64 dropped_packet_total_count;
__u8 flow_end_reason;
 __u64 common_properties_id;
__u64  observation_point_id;
__u16 icmp_type_code_ipv6;
unsigned char mpls_top_label_ipv6_address[16];
__u32 linecard_id;
__u32 port_id;
__u32 metering_process_id;
__u32 exporting_process_id;
__u16 template_id;
__u8 wlan_channel_id;
char wlan_ssid[256];
__u64 flow_id;
__u32 observation_domain_id;
__u64 flow_start_seconds;
__u64 flow_end_seconds;
__u64 flow_start_milliseconds;
__u64 flow_end_milliseconds;
__u64 flow_start_microseconds;
__u64 flow_end_microseconds;
__u64 flow_start_nanoseconds;
__u64 flow_end_nanoseconds;
__u32 flow_start_delta_microseconds;
__u32 flow_end_delta_microseconds;
__u64 system_init_time_milliseconds;
__u32 flow_duration_milliseconds;
__u32 flow_duration_microseconds;
__u64 observed_flow_total_count;
__u64 ignored_packet_total_count;
__u64 ignored_octet_total_count;
__u64 not_sent_flow_total_count;
__u64 not_sent_packet_total_count;
__u64 not_sent_octet_total_count;
unsigned char destination_ipv6_prefix[16];
unsigned char  source_ipv6_prefix[16];
 __u64 post_octet_total_count;
__u64 post_packet_total_count;
__u64 flow_key_indicator;
__u64 post_mcast_packet_total_count;
__u64  post_mcast_octet_total_count;
__u8 icmp_type_ipv4;
__u8 icmp_code_ipv4;
__u8 icmp_type_ipv6;
__u8 icmp_code_ipv6;
__u16 udp_source_port;
__u16 udp_destination_port;
__u16 tcp_source_port;
__u16 tcp_destination_port;
__u32 tcp_sequence_number;
__u32 tcp_acknowledgement_number;
__u16 tcp_window_size;
__u16 tcp_urgent_pointer;
__u8 tcp_header_length;
__u8 ip_header_length;
__u16 total_length_ipv4;
 payload_length_ipv6;
 ip_ttl;
 next_header_ipv6;
 mpls_payload_length;
 ip_diffserv_codepoint;
 ip_precedence;
 fragment_flags;
 octet_delta_sum_of_squares;
 octet_total_sum_of_squares;
 mpls_top_label_ttl;
 mpls_label_stack_length;
 mpls_label_stack_depth;
 mpls_top_label_exp;
 ip_payload_length;
 udp_message_length;
 is_multicast;
 ipv4ihl;
 ipv4options;
 tcp_options;
 padding_octets;
 collector_ipv4_address;
 collector_ipv6_address;
 export_interface;
 export_protocol_version;
 export_transport_protocol;
 collector_transport_port;
 exporter_transport_port;
 tcp_syn_total_count;
 tcp_fin_total_count;
 tcp_rst_total_count;
 tcp_psh_total_count;
 tcp_ack_total_count;
 tcp_urg_total_count;
 ip_total_length;
 post_nat_source_ipv4_address;
 post_nat_destination_ipv4_address;
 post_napt_source_transport_port;
 post_napt_destination_transport_port;
 nat_originating_address_realm;
 nate_vent;
 initiator_octets;
 responder_octets;
 firewall_event;
 ingress_vrf_id;
 egress_vrf_id;
 vrf_name;
 post_mpls_top_label_exp;
 tcp_window_scale;
 bi_flow_direction;
 ethernet_header_length;
 ethernet_payload_length;
 ethernet_total_length;
 dot1q_vlan_id;
 dot1q_priority;
 dot1q_customer_vlan_id;
 dot1q_customer_priority;
 metro_evc_id;
 metro_evc_type;
 pseudowire_id;
 pseudowire_type;
 pseudowire_control_word;
 ingress_physical_interface;
 egress_physical_interface;
 post_dot1q_vlan_id;
 post_dot1q_customer_vlan_id;
 ethernet_type;
 post_ip_precedence;
 collection_time_milliseconds;
 export_sctp_stream_id;
 max_export_seconds;
 maxflow_end_seconds;
 message_scope;
 min_export_seconds;
 minflow_start_seconds;
 session_scope;
 maxflow_end_microseconds;
 maxflow_end_milliseconds;
 maxflow_end_nanoseconds;
 minflow_start_microseconds;
 minflow_start_milliseconds;
 minflow_start_nanoseconds;
 data_records_reliability;
 observation_point_type;
 new_connection_delta_count;
 connection_sum_duration_seconds;
 connection_transaction_id;
 post_nat_source_ipv6_address;
 post_nat_destination_ipv6_address;
 nat_pool_id;
 nat_pool_name;
 anonymization_flags;
 anonymization_technique;
 information_element_index;
 bgp_validity_state;
 ipsec_spi;
 gre_key;
 nat_type;
 initiator_packets;
 responder_packets;
 selection_sequence_id;
 selector_id;
 information_element_id;
 selector_algorithm;
 sampling_packet_interval;
 sampling_packet_space;
 sampling_timeinterval;
 sampling_time_space;
 sampling_size;
 sampling_population;
 sampling_probability;
 data_link_frame_size;
 selector_id_total_pkts_observed;
 selector_id_total_pkts_selected;
 absolute_error;
 relative_error;
 observation_time_seconds;
 observation_time_milliseconds;
 observation_time_microseconds;
 observation_time_nanoseconds;
 digest_hash_value;
 hash_ip_payload_offset;
 hash_ip_payload_size;
 hash_output_range_min;
 hash_output_range_max;
 hash_selected_range_min;
 hash_selected_range_max;
 hash_digest_output;
 hash_initial_iser_value;
 upper_ci_limit;
 lower_ci_limit;
 confidence_level;
 information_element_data_type;
 information_element_range_begin;
 information_element_range_end;
 information_element_semantics;
 information_element_units;
 private_enterprise_number;
 layer2_segment_id;
 layer2_octet_delta_count;
 layer2_octet_total_count;
 ingress_unicast_packet_total_count;
 ingress_multicast_packet_total_count;
 ingress_broadcast_packet_total_count;
 egress_unicast_packet_total_count;
 egress_broadcast_packet_total_count;
 monitoring_interval_start_milliseconds;
 monitoring_interval_end_milliseconds;
 port_range_start;
 port_range_end;
 port_range_stepsize;
 port_range_num_ports;
 sta_mac_address;
 sta_ipv4_address;
 wtp_mac_address;
 ingress_interface_type;
 egress_interface_type;
 rtp_sequence_number;
 original_flows_present;
 original_flows_initiated;
 original_flows_completed;
 distinct_count_of_source_ipaddress;
 distinct_count_of_destination_ipaddress;
 distinct_count_of_source_ipv4_address;
 distinct_count_of_destination_ipv4_address;
 distinct_count_of_source_ipv6_address;
 distinct_count_of_destination_ipv6_address;
 value_distribution_method;
 rfc3550_jitter_milliseconds;
 rfc3550_jitter_microseconds;
 rfc3550_jitter_nanoseconds;
 dot1q_dei;
 dot1q_customer_dei;
 flow_selector_algorithm;
 flow_selected_octet_delta_count;
 flow_selected_packet_delta_count;
 flow_selected_flow_delta_count;
 selector_id_total_flows_observed;
 selector_id_total_flows_selected;
 sampling_flow_interval;
 sampling_flow_spacing;
 flow_sampling_time_interval;
 flow_sampling_time_spacing;
 hash_flow_domain;
 transport_octet_delta_count;
 transport_packet_delta_count;
 original_exporter_ipv4_address;
 original_exporter_ipv6_address;
 original_observation_domain_id;
 intermediate_process_id;
 ignored_data_record_total_count;
 data_link_frame_type;
 section_offset;
 section_exported_octets;
 dot1q_service_instance_tag;
 dot1q_service_instance_id;
 dot1q_service_instance_priority;
 dot1q_customer_source_mac_address;
 dot1q_customer_destination_maca_ddress;
 post_layer2_octet_delta_count;
 post_mcast_layer2_octet_delta_count;
 post_layer2_octet_total_count;
 post_mcast_layer2_octet_total_count;
 minimum_layer2_total_length;
 maximum_layer2_total_length;
 dropped_layer2_octet_delta_count;
 dropped_layer2_octet_total_count;
 ignored_layer2_octet_total_count;
 not_sent_layer2_octet_total_count;
 layer2_octet_delta_sum_of_squares;
 layer2_octet_total_sum_of_squares;
 layer2_frame_delta_count;
 layer2_frame_total_count;
 pseudowire_destination_ipv4_address;
 ignored_layer2_frame_total_count;
 mib_object_value_integer;
 mib_object_value_octet_string;
 mib_object_value_oid;
 mib_object_value_bits;
 mib_object_value_ipaddress;
 mib_object_value_counter;
 mib_object_value_gauge;
 mib_object_value_time_ticks;
 mib_object_value_unsigned;
 mib_sub_identifier;
 mib_index_indicator;
 mib_capture_time_semantics;
 http_status_code;
 source_transport_ports_limit;
 nat_instance_id;
 nat_quota_exceeded_event;
 nat_threshold_event;
 http_user_agent;
 http_content_type;
 http_reason_phrase;
 max_session_entries;
 max_bib_entries;
 max_entries_per_user;
 max_subscribers;
 max_fragments_pending_reassembly;
 address_pool_high_threshold;
 address_pool_low_threshold;
 address_port_mapping_high_threshold;
 address_port_mapping_low_threshold;
 address_port_mapping_per_user_high_threshold;
 globaladdressmappinghighthreshold;
 vpn_identifier;
 bgp_community;
 srh_flags_ipv6;
 srh_tag_ipv6;
 srh_segment_ipv6;
 srh_active_segment_ipv6;
 srh_segments_ipv6_left;
 srh_ipv6_section;
 srh_ipv6_active_segment_type;
 srh_segment_ipv6_locator_length;
 srh_segment_ipv6_endpoint_behavior;
 transport_checksum;
 gtpu_flags;
 gtpu_msg_type;
 gtpu_te_id;
 gtpu_sequenc_enum;
 gtpu_qfi;
 gtpu_pdu_type;
 tcp_options_full;
 tcp_shared_option_exid_16;
 tcp_shared_option_exid_32;
 udp_safe_options;
 udp_unsafe_options;
 udp_exid;
};

#endif